name: tmate

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 14400
    runs-on: ubuntu-22.04
    
    steps:
    - name: install
      run: |
        sudo apt update && sudo apt install -y tmate curl
        
    - name: generate tmate session
      run: |
        tmate -S ${{ github.repository }}-session
